import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Sanity Blog (Site)",
  description: "Generated by Next + Sanity",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header>
          <Link
            href="/"
            className="bg-gradient-to-r from-cyan-400 to-blue-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Derrick
          </Link>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
